@startuml
'https://plantuml.com/class-diagram

VariantType <--o ComponentFieldDefinition
ComponentFieldDefinition <--* Component
Component <--* World
ComponentType <--* ComponentInfo
ComponentInfo <--* World

enum VariantType

class ComponentFieldDefinition {
    String name
    VariantType type
}

class Component {
    set_field(String name, Variant value)
    Variant get_field(String name)
}

class ComponentInfo {
    hash: u64
}

class World {
    component_definitions: HashMap<ComponentInfo, Vec<ComponentFieldDefinition>>
    component_names: HashMap<String, ComponentInfo>
    entities: Vec<uuid>
    components: HashMap<String, Vec<Box<dyn Component>>>

    register_component(&mut self, name: String, fields: Vec<ComponentFieldDefinition>) -> Result<ComponentInfo, String>
}

@enduml