@startuml
'https://plantuml.com/class-diagram
class Godot.StringName

class Variant {
}
enum Variant.Type

class ComponentFieldDefinition {
    Godot.StringName name
    Variant.Type type
}

interface Component {
    Vec<ComponentFieldDefinition> get_fields()
    void set_field(Godot.StringName name, Variant value)
    Variant get_field(Godot.StringName name)
}


@enduml