[package]
name = "godot-component-system"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["staticlib"]

[dependencies]
gcs = { path = "gcs"}
gcs-cxx = { path = "gcs-cxx"}