[package]
name = "gcs"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
uuid = {version = "0.8", features=["serde", "v4"]}
godot-cxx-common = { registry = "ktra", version="0.1.0"}